# -*- coding: utf-8 -*-
"""最終版.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ma32zz4hvk63ZJdP8tHinreR2-iUpXux
"""

!pip install -q streamlit google-generativeai

import os
from google.colab import userdata

# 依照講義第2頁，使用 userdata 讀取金鑰
try:
    api_keys = userdata.get('Gemini_Key')

    # 自動建立 Streamlit 的隱藏安全金鑰資料夾與檔案
    os.makedirs(".streamlit", exist_ok=True)
    with open(".streamlit/secrets.toml", "w", encoding="utf-8") as f:
        f.write(f'Gemini_Key = "{api_keys}"\n')

    print("✅ 安全防禦成功：已自動讀取 Colab 小鑰匙金鑰，並加密橋接至 Streamlit 系統，程式碼內無任何密碼字串！")
except Exception as e:
    print(f"❌ 讀取失敗，請確認您是否已在 Colab 左側小鑰匙設定了 'GEMINI_KEY' 並開啟存取權限。錯誤: {e}")

import json

# 🎯 擴充至 30 題大滿貫經典熱門海龜湯題庫
# 程式與資料分離架構：主程式 app.py 完全不需要更動，網頁重整後會自動載入這 30 題！
riddle_bank_data = [
    {
        "title": "01. 愛犬",
        "riddle": "一個女孩獨居，陪伴她的只有愛犬。半夜醒來，她聽到房間角落傳來一下一下的水滴聲，非常害怕。於是她把手放到了床邊，讓愛犬舔了舔她的手，感覺到溫暖後漸漸又睡著了。第二天，她發現狗死在浴室，牆上用血寫著：「人也會舔手」。請問發生了什麼事？",
        "secret_answer": "水滴聲其實不是水龍頭漏水，而是兇手殺了狗之後，將狗倒掛在浴室滴血的聲音。女孩以為床邊舔她手的是愛犬，但實際上那時狗已經死了，躲在床底下的兇手模仿狗去舔她的手。"
    },
    {
        "title": "02. 看病",
        "riddle": "一個人坐火車去臨城看眼疾，看完之後手術非常成功，他的病全好了。但在回程的路上，火車經過一個隧道時，這個人卻突然跳車自殺了。請問發生了什麼事？",
        "secret_answer": "這個人原本是個雙目失明的盲人，開刀後終於恢復了視力。回程火車經過隧道時，四周突然陷入一片漆黑。他誤以為自己的病又復發、再度失明了，絕望之下無法接受打擊，便跳車自殺了。"
    },
    {
        "title": "03. 100元錢",
        "riddle": "小明在圖書館看書，在一本書裡意外翻到了100塊錢，但是他確認完這張鈔票後卻放聲大哭了。為什麼？",
        "secret_answer": "這100元是小明多年前失明前放進去的。小明現在是個盲人，在圖書館看的是「盲文（點字）書」，當他摸到並確認這張當年的100元時，想起了過去擁有視力的快樂時光，悲從中來便放聲大哭。"
    },
    {
        "title": "04. 電梯",
        "riddle": "一個人住在高層公寓的17樓。每天下班回家，如果下雨，他總是乘電梯直接到他住的17樓；如果沒下雨，他會坐電梯到11樓，然後走樓梯走到17樓。請問為什麼？",
        "secret_answer": "這個人身患侏儒症（身高非常矮）。電梯的按鈕他平時最高只能夠到11樓的按鈕。如果下雨，他可以用雨傘夠到17樓的按鈕；如果沒下雨，他就只能按到11樓再爬樓梯。"
    },
    {
        "title": "05. 仙人掌",
        "riddle": "一個男人在荒涼的沙漠中，倒在一株仙人掌旁死去。仙人掌上還貼著一張他自己寫的紙條。發生了什麼事？",
        "secret_answer": "這個男人在沙漠中迷失了方向，瀕臨渴死。這張貼在仙人掌上的紙條是他之前走過時，為了做標記留下來的。當他不知不覺再次繞回到這株仙人掌時，絕望地發現自己一直在原地打轉，喪失了求生意志而死。"
    },
    {
        "title": "06. 手滑",
        "riddle": "我在和閨蜜視訊聊天，忽然我的手機掉在了地上。螢幕另一端的閨蜜當場嚇傻了，而我也死了。為什麼？",
        "secret_answer": "我和閨蜜此時正在一棟高樓的邊緣進行極限天台攀爬，我一邊用手機跟她視訊聊天炫耀。突然我手滑，手機掉了下去，連帶著我也一起墜樓身亡，閨蜜全程目睹了墜樓過程而被嚇傻。"
    },
    {
        "title": "07. 原味海龜湯",
        "riddle": "一個男子在一家餐廳喝了一碗海龜湯，出餐廳後他就自殺了。請問發生了什麼事？",
        "secret_answer": "男子過去曾和戀人、朋友遭遇海難困在荒島。當時朋友做了一碗「海龜湯」給他喝才讓他活下來，但戀人卻失蹤了。如今他在餐廳喝到真正的海龜湯，發現味道完全不同，才明白當年在荒島上喝的根本不是海龜湯，而是他死去戀人的肉，崩難之下便自殺了。"
    },
    {
        "title": "08. 冰塊密室",
        "riddle": "一個男子被發現吊死在一個完全空曠的密室中央，房間裡沒有任何家具或可以墊腳的物品，只有地上的一灘水。請問他是怎麼自殺的？",
        "secret_answer": "他是站在一個巨大的冰塊上，把繩子套在脖子上。隨著時間過去，冰塊完全融化成了地上的那一灘水，他也因此被吊死了。"
    },
    {
        "title": "09. 燈塔管理員",
        "riddle": "一個男人關掉燈後上床睡覺。第二天早上他醒來，看過早報後便開窗跳樓自殺了。請問發生了什麼事？",
        "secret_answer": "這個男人是燈塔的管理員。昨晚他喝醉了，誤把燈塔的指示燈當成普通的電燈關掉。隔天早上他在報紙上看到一艘大客輪因為沒有燈塔導航而觸礁沉沒，死傷慘重。他深感自責與愧疚，便跳樓自殺了。"
    },
    {
        "title": "10. 第53張撲克牌",
        "riddle": "一個男人被發現陳屍在密室的桌子旁，手上緊緊抓著幾張撲克牌，而地上散落著其餘的牌。經過警方清點，現場總共有53張撲克牌。請問他是怎麼死的？",
        "secret_answer": "這個男人在地下賭場出千（作弊）。他偷偷在袖子裡藏了一張牌，結果被對手當場抓包。清點撲克牌時發現多了一張牌（一副牌只有52張不含鬼牌），憤怒的對手直接掏出槍將他當場射殺。"
    },
    {
        "title": "11. 致命的稻草",
        "riddle": "一個男人赤裸地死在荒無人煙的麥田中央，他的手裡緊緊握著一根稻草，身邊沒有任何交通工具或衣物。請問他是怎麼死的？",
        "secret_answer": "他和其他幾個人乘坐熱氣球飛過麥田，但熱氣球燃料不足且嚴重超載，開始急速下墜。大家扔光了所有行李和衣服後依然不夠，於是決定抽籤（抽稻草），抽中短的人必須跳下去。這個人不幸抽中了短稻草，只好跳下熱氣球摔死。"
    },
    {
        "title": "12. 酒吧打嗝",
        "riddle": "一個男人走進酒吧，向調酒師要一杯水。調酒師突然從櫃檯下掏出一把槍指向他。男人愣了一下，隨後高興地說了聲「謝謝」便轉身離開。請問為什麼？",
        "secret_answer": "這個男人走進酒吧是因為他一直在瘋狂打嗝，想喝水緩解。調酒師看出了他的狀況，故意掏出槍來嚇他。驚嚇成功治好了他的打嗝，因此男人非常感激，不需要喝水就禮貌地離開了。"
    },
    {
        "title": "13. 毒蘋果",
        "riddle": "母親切開一個蘋果，分了一半給女兒，自己也吃了一半。兩個人吃完後，只有女兒中毒身亡，母親卻安然無恙。既然蘋果本身沒有毒，請問這是怎麼做到的？",
        "secret_answer": "毒藥其實塗在切蘋果的刀子上，而且只塗了刀刃的其中一面。當母親切開蘋果時，有毒的那一面刀刃切到了分給女兒的那一半蘋果，沒毒的那一面切到了母親的那一半。"
    },
    {
        "title": "14. 姐姐的葬禮",
        "riddle": "一個女孩在母親的葬禮上遇到了一位極其帥氣的男子，並對他一見鍾情。遺憾的是，葬禮結束後她忘記留男子的聯絡方式。幾天後，女孩竟然殘忍地殺害了自己的親姐姐。請問她為什麼要這麼做？",
        "secret_answer": "女孩為了能再次見到那位帥氣的男子。她認為既然那個男子會來參加母親的葬禮，代表他是家族的朋友，那麼只要家裡再辦一次葬禮（比如姐姐的葬禮），那個男子就一定會再次出現。"
    },
    {
        "title": "15. 焦黑潛水員",
        "riddle": "在一場嚴重的森林大火被撲滅後，護林員在森林中央的一棵焦黑大樹上，發現了一具穿著完整潛水裝備（潛水鏡、氧氣瓶、蛙鞋）的潛水員屍體。請問他為什麼會死在這裡？",
        "secret_answer": "森林大火時，消防隊出動直升機前往附近的海洋汲水滅火。這名潛水員當時正在海裡潛水，不幸連同海水一起被吸進了直升機的大型水袋中。隨後，直升機飛到森林上空灑水，潛水員便從高空摔在樹上摔死了。"
    },
    {
        "title": "16. 沉默的鸚鵡",
        "riddle": "小明花了大筆金錢在寵物店買了一隻鸚鵡，老闆拍胸脯保證這隻鸚鵡「聽到什麼就會重複說什麼」。但小明回家後對牠說了一整週的話，鸚鵡卻一個字也沒說過。然而老闆並沒有騙人。請問為什麼？",
        "secret_answer": "這隻鸚鵡是一隻「聾子（聽不到聲音）」。老闆說牠「聽到什麼就會重覆說什麼」，但因為牠什麼都聽不到，所以自然什麼也重複不出來。"
    },
    {
        "title": "17. 香草汽車",
        "riddle": "一個男人每天開車去買冰淇淋。他發現一個詭異的規律：只要他買香草口味，車子開走時就會發動失敗；但如果買巧克力或草莓口味，車子就能順利發動。這不是靈異事件，請問原因是什麼？",
        "secret_answer": "這是汽車的「氣阻（Vapor Lock）」現象。香草口味最熱銷，店家將其提前包裝好放在櫃檯前，男人一去就能馬上拿到並離開，引擎熄火時間太短，導致高溫產生氣阻無法發動。而其他口味需要現挖耗時較長，這段時間剛好讓引擎降溫成功發動。"
    },
    {
        "title": "18. 外科醫生的戒指",
        "riddle": "一位著名外科醫生為病人做完一場極其成功的手術後，走進洗手池洗手。當他洗完手端詳著自己的雙手時，突然臉色大變，隨即在洗手間裡自殺了。請問為什麼？",
        "secret_answer": "醫生洗手時，突然發現自己手指上的結婚戒指不見了。他猛然想起，剛才手術縫合前，戒指可能不小心掉進了病人的腹腔內，並被縫在了裡面。而此時病人已經過世，他知道自己犯了不可挽回的醫療事故，崩潰下決定自殺。"
    },
    {
        "title": "19. 跳針的廣播",
        "riddle": "一個男人一邊開車一邊聽著收音機裡的現場直播音樂節目。突然，他臉色慘白，猛踩煞車將車停在路邊，隨後從手套箱掏出手槍自殺了。請問發生了什麼事？",
        "secret_answer": "這個男人其實是一名電台的主持人。他為了營造自己此時正在電台「現場直播」工作的不在場證明，提前錄製好了一段錄音帶在電台播放，自己則偷偷溜回家殺害妻子。然而，當他在車裡收聽時，發現錄音帶因為故障開始不斷跳針重複。他知道自己的偽裝徹底敗露，絕望下開槍自殺。"
    },
    {
        "title": "20. 深夜敲門聲",
        "riddle": "一個男人獨自住在懸崖邊的小木屋裡。某天深夜狂風暴雨，他忽然聽到門外傳來急促的敲門聲。他急忙跑去開門，外頭卻一片漆黑，什麼人也沒有。當晚這個過程重複了幾次。第二天，懸崖下方發現了一具摔得血肉模糊的登山客屍體。請問這是怎麼回事？",
        "secret_answer": "那座小木屋的門是「向外打開」的。深夜迷路的登山客好不容易走到木屋前敲門求救。主人一聽到敲門聲就熱心地「向外推開門」，這一推剛好把站在懸崖邊緣的登山客給推下了懸崖。主人關上門後，登山客又拼命爬上來敲門，結果又被推下去，最後終於傷重摔死。"
    },
    {
        "title": "21. 空難奇蹟",
        "riddle": "一架民航客機不幸在山區墜毀，機身斷成兩截。救援隊趕到後遺憾地宣布：「飛機上的每一個人（Every single person）都罹難了。」然而，幾天後的生還者名單上，卻赫然出現了兩個人的名字。請問這怎麼可能？",
        "secret_answer": "這是一個英文單字字面意思的文字遊戲。「Every single person」在英文中也可以翻譯成「每一個單身的人」。那兩位生還者是一對「恩愛的夫妻」，他們不是單身漢，所以雖然「單身的人都死了」，但夫妻倆幸運地活了下來。"
    },
    {
        "title": "22. 驚悚的鏡子",
        "riddle": "一個通緝犯花重金做了徹底的整容手術，成功換了一張臉。手術非常成功，當護士幫他拆開臉上的繃帶時，他興奮地拿起鏡子看了一眼，隨即發出驚恐的慘叫，心臟病發當場嚇死了。請問他看到了什麼？",
        "secret_answer": "幫他做手術的整容醫生，其實是當年被這個通緝犯殘忍殺害的受害者的親生哥哥。醫生在手術中故意把通緝犯的臉，整得跟「通緝令上的照片一模一樣」。通緝犯在鏡中看到自己換完臉竟然變成了通緝令本人，心理防線崩潰被活活嚇死。"
    },
    {
        "title": "23. 神祕包裹",
        "riddle": "男子收到一個沉甸甸的包裹，打開一看裡面竟然是一隻血淋淋的「人類斷手」。男子仔細檢查了斷手後，滿意地將它重新包裝好，填上另一個地址郵寄給了第三個人。請問他們在幹什麼？",
        "secret_answer": "他們是多年前一場海難的倖存者，當時有四個人被困在荒島。為了活下去，他們約定每人輪流砍下一隻手當作大家的食物。在前三個人都切了手之後，他們迎來了救援。回到社會後，那三個切了手的人要求第四個人履行承諾，第四個人只好在醫院鋸掉手，並郵寄給其他人檢查。"
    },
    {
        "title": "24. 融化的冰塊",
        "riddle": "兩名男子點了完全相同的冰鎮毒果汁。其中一人因為趕時間，大口大口快速喝完就離開了；另一人則一邊看報紙一邊慢條斯理地品嚐。結果，慢喝的男子當場中毒身亡，快喝的男子卻一點事也沒有。請問為什麼？",
        "secret_answer": "毒藥其實不是混在果汁裡，而是被凍在「冰塊」中。快喝的男子因為喝得非常快，冰塊還來不及融化他就喝完離開了；而慢喝的男子因為喝得慢，冰塊在杯子裡完全融化，毒藥全部釋放進果汁中，導致他中毒身亡。"
    },
    {
        "title": "25. 絕望的天鵝肉",
        "riddle": "一個男人在餐館點了一道「天鵝肉」，他僅僅嚐了一口，眼淚就止不住地流了下來，隨後走出餐館自殺了。請問隱藏的真相是什麼？",
        "secret_answer": "幾年前，男人和妻子遭遇海難流落荒島。在快要餓死時，妻子生病去世了，為了讓男人活下去，男人的父親給他做了一碗肉湯，騙他是抓到的「天鵝肉」。如今年輕人在餐館吃到真正的天鵝肉，發現味道完全不同，才明白當年吃的是妻子的肉，悲痛欲絕下自殺。"
    },
    {
        "title": "26. 暴雨不濕髮",
        "riddle": "在一個傾盆大雨的深夜，一個男人沒有帶任何雨具（傘、帽子、雨衣），在毫無遮蔽的大街上走了足足半個小時。當他回到家時，全身上下的衣服鞋襪全都濕透了，但他的頭髮卻連一根都沒有濕。請問為什麼？",
        "secret_answer": "原因很簡單，因為這個男人是一個「禿頭（完全沒有頭髮）」。既然本來就沒有頭髮，自然就不存在頭髮被淋濕的問題。"
    },
    {
        "title": "27. 高級飯店的床底",
        "riddle": "一對夫婦入住了一家高級飯店。進房後，丈夫總覺得房間裡有一股淡淡的死老鼠腐臭味，但妻子卻說什麼也聞不到。隔天早上，丈夫在洗頭時，腐臭味突然變得極其濃烈，隨後他在房間裡瘋狂尖叫。請問他發現了什麼？",
        "secret_answer": "腐臭味其實來自於「床墊下方藏著的一具腐屍」。昨晚睡覺時，丈夫那一側的床墊下方剛好卡著屍體的頭部，所以他聞得到；而隔天早上，屍體因為體內氣體膨脹，腐血滲透了床墊，丈夫這才驚恐地發現自己昨晚竟然睡在屍體正上方。"
    },
    {
        "title": "28. 致命的生日禮物",
        "riddle": "一個老爺爺躺在醫院的加護病房，靠著呼吸器維持生命。中午，家族的所有親戚一起來幫老爺爺慶祝生日，但當大家高高興興吹熄生日蛋糕的蠟燭後，老爺爺突然痛苦地掙扎幾下便去世了。請問為什麼？",
        "secret_answer": "家族親戚們提著一個精美的「電動旋律生日蛋糕」和「彩色LED生日燈」來慶祝。因為病房牆上的插座不夠用，某個親戚貪圖方便，竟然偷偷把老爺爺「呼吸器的插頭拔掉」，改插上生日蛋糕的特效燈。大家吹熄蠟燭後燈光變暗，才發現老爺爺已經因為斷電缺氧而死。"
    },
    {
        "title": "29. 磨刀不誤砍柴工",
        "riddle": "兩名伐木工在森林裡比賽鋸木頭。甲工人連續工作8個小時，一刻也不敢休息；乙工人每工作50分鐘就會坐在旁邊休息10分鐘。到了下班清點時，乙工人鋸的木頭數量竟然比甲工人整整多出一倍。請問乙工人休息時在幹嘛？",
        "secret_answer": "乙工人每工作50分鐘，在休息的那10分鐘裡，並不是在偷懶，而是在用專用工具「磨利他的鋸子」。甲工人雖然一刻不停，但鋸子越來越鈍，效率極低；乙工人則始終保持鋸子在最鋒利的狀態。"
    },
    {
        "title": "30. 致命的香味",
        "riddle": "一位科學家在密閉的實驗室裡做實驗，突然他聞到了一股淡淡的植物香味，他臉色大變，急忙想往外跑，但還沒走到門口就倒地身亡了。請問他是怎麼死的？",
        "secret_answer": "這位科學家正在研發一種無色無味的「致命劇毒氣體」。為了防止外洩時無法察覺，他在毒氣中刻意添加了一種「特殊的植物香味」作為警告標誌。當他聞到香味時，代表毒氣已經嚴重外洩，他雖然立刻反應過來，但吸入毒氣過深，隨即毒發身亡。"
    }
]

# 將 30 題大滿貫資料寫入外部 JSON 檔案
with open('riddles.json', 'w', encoding='utf-8') as f:
    json.dump(riddle_bank_data, f, ensure_ascii=False, indent=2)

print("Status: 🎯 成功擴充至 30 題大滿貫經典題目，並已更新題庫檔案：riddles.json！")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import google.generativeai as genai
# import json
# import os
# 
# # ==========================================
# # 1. 遊戲基礎設定與介面初始化
# # ==========================================
# st.set_page_config(page_title="AI 海龜湯情境猜謎系統", layout="wide", page_icon="🐢")
# 
# st.html("""
# <style>
# 
# /* ===== 全站背景 ===== */
# [data-testid="stAppViewContainer"]{
#     background:
#     radial-gradient(circle at 20% 20%, rgba(0,212,255,.18), transparent 30%),
#     radial-gradient(circle at 80% 30%, rgba(168,85,247,.18), transparent 30%),
#     radial-gradient(circle at 50% 80%, rgba(0,212,255,.10), transparent 40%),
#     linear-gradient(
#         135deg,
#         #020617 0%,
#         #0f172a 40%,
#         #111827 70%,
#         #030712 100%
#     );
#     color:white;
# }
# 
# /* ===== ✨ 徹底消滅頂部與提問框周圍的橫向大白條 ===== */
# [data-testid="stHeader"],
# [data-testid="stBottom"],
# [data-testid="stBottomBlockContainer"],
# div[data-testid="stBottom"] > div {
#     background-color: transparent !important;
#     background: transparent !important;
# }
# 
# /* ===== 流光動畫 ===== */
# [data-testid="stAppViewContainer"]::before{
#     content:"";
#     position:fixed;
#     top:-50%;
#     left:-50%;
#     width:200%;
#     height:200%;
#     background:
#     linear-gradient(
#         90deg,
#         transparent,
#         rgba(0,212,255,.05),
#         transparent,
#         rgba(168,85,247,.05),
#         transparent
#     );
#     animation: flow 15s linear infinite;
#     pointer-events:none;
# }
# 
# @keyframes flow{
#     from{ transform:rotate(0deg); }
#     to{ transform:rotate(360deg); }
# }
# 
# /* ===== 主內容 ===== */
# .main .block-container {
#     background-image:
#         linear-gradient(rgba(15, 23, 42, 0.75), rgba(15, 23, 42, 0.75)),
#         linear-gradient(135deg, #00d4ff, #8b5cf6, #ff007f, #00ffcc, #00d4ff) !important;
#     background-origin: border-box !important;
#     background-clip: padding-box, border-box !important;
#     background-size: 300% 300% !important;
#     border: 2px solid transparent !important;
#     border-radius: 20px !important;
#     backdrop-filter: blur(12px);
#     padding: 2rem;
#     animation: rgb-border-flow 8s ease infinite !important;
# }
# 
# @keyframes rgb-border-flow {
#     0% {
#         background-position: 0% 50% !important;
#         box-shadow:
#             0 0 20px rgba(0, 212, 255, 0.25),
#             0 0 40px rgba(0, 212, 255, 0.1);
#     }
#     50% {
#         background-position: 100% 50% !important;
#         box-shadow:
#             0 0 30px rgba(255, 0, 127, 0.35),
#             0 0 60px rgba(139, 92, 246, 0.15);
#     }
#     100% {
#         background-position: 0% 50% !important;
#         box-shadow:
#             0 0 20px rgba(0, 212, 255, 0.25),
#             0 0 40px rgba(0, 212, 255, 0.1);
#     }
# }
# 
# /* ===== 標題發光 ===== */
# h1{
#     color:white !important;
#     text-shadow:
#         0 0 10px #00d4ff,
#         0 0 20px #00d4ff,
#         0 0 40px #8b5cf6;
# }
# 
# /* ===== 所有常規文字 ===== */
# h2, h3, p, li, label, span, [data-testid="stMarkdownContainer"] p {
#     color: white !important;
# }
# 
# /* ===== 側邊欄基礎樣式 ===== */
# section[data-testid="stSidebar"]{
#     background: linear-gradient(180deg, rgba(5,10,20,.95), rgba(15,23,42,.95));
#     border-right:1px solid rgba(0,212,255,.3);
# }
# section[data-testid="stSidebar"] * {
#     color: white !important;
# }
# 
# /* ===== 🔵 經典核心設計：主畫面按鈕與「返回首頁」按鈕 ===== */
# .stButton button{
#     background: linear-gradient(90deg, #00d4ff, #8b5cf6) !important;
#     color:white !important;
#     border:none !important;
#     border-radius:12px !important;
#     font-weight:bold !important;
#     transition: 0.3s cubic-bezier(0.25, 0.8, 0.25, 1) !important;
# }
# .stButton button:hover{
#     transform: translateY(-2px) !important;
#     box-shadow: 0 0 15px #00d4ff, 0 0 30px #00d4ff, 0 0 50px #8b5cf6 !important;
# }
# 
# /* ===== 💡 極致極簡：針對「已完成的題目紀錄」按鈕全面去框 ===== */
# /* 平常狀態：純白底、深色字、絕無邊框與外框線 */
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button,
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button * {
#     background: #ffffff !important;
#     color: #0f172a !important;
#     border: none !important;
#     outline: none !important;
#     box-shadow: none !important;
#     border-radius: 12px !important;
#     transition: transform 0.2s ease-in-out !important; /* 讓放大縮小更平滑 */
# }
# 
# /* 🏁 靠近時（Hover）、點擊時（Active）、聚焦時（Focus）：純粹放大，消滅任何框線與藍框 */
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button:hover,
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button:focus,
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button:active,
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button:hover *,
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button:focus *,
# section[data-testid="stSidebar"] div[data-testid="stElementContainer"]:has(button) ~ div[data-testid="stElementContainer"]:has(button) button:active * {
#     background: #ffffff !important;
#     color: #0f172a !important;
#     border: none !important;
#     outline: none !important;
#     box-shadow: none !important;
#     transform: scale(1.05) !important; /* 只保留這個變大效果 */
# }
# 
# /* ===== 強制讓選單框與下拉選單內的字體全變黑色 ===== */
# div[data-baseweb="select"] *,
# div[data-baseweb="popover"] *,
# [data-baseweb="menu"] * {
#     color: #000000 !important;
# }
# 
# /* ===== Radio ===== */
# div[role="radiogroup"]{
#     background:rgba(15,23,42,.6);
#     border-radius:15px;
#     padding:10px;
# }
# 
# /* ===== 捲軸 ===== */
# ::-webkit-scrollbar{ width:8px; }
# ::-webkit-scrollbar-thumb{ background:#00d4ff; border-radius:20px; }
# 
# </style>
# """)
# 
# # ---- 核心資安：從 Secrets 讀取金鑰 ----
# api_key = ""
# if "Gemini_Key" in st.secrets:
#     api_key = st.secrets["Gemini_Key"]
# else:
#     api_key_input = st.sidebar.text_input("請輸入 API Key：", type="password")
#     api_key = api_key_input
# 
# if not api_key:
#     st.warning("⚠️ 請先設定 GEMINI_KEY 以啟動遊戲")
#     st.stop()
# 
# genai.configure(api_key=api_key)
# 
# # ==========================================
# # 2. 讀取外部題庫與初始化成就紀錄
# # ==========================================
# try:
#     with open('riddles.json', 'r', encoding='utf-8') as f:
#         riddle_bank = json.load(f)
# except FileNotFoundError:
#     st.error("❌ 找不到題庫檔案 'riddles.json'！")
#     st.stop()
# 
# if "completed_riddles" not in st.session_state:
#     st.session_state.completed_riddles = []
# if "completed_histories" not in st.session_state:
#     st.session_state.completed_histories = {}
# if "page" not in st.session_state:
#     st.session_state.page = "home"
# 
# # 建立安全的 Callback 導航港口
# def navigate_to_solved_riddle(title):
#     st.session_state.selectbox_title = title
#     st.session_state.current_title = title
#     if title in st.session_state.completed_histories:
#         st.session_state.chat_history = list(st.session_state.completed_histories[title])
#     else:
#         st.session_state.chat_history = []
# 
# # ==========================================
# # 3. 頁面分流架構 (首頁 vs 遊戲頁)
# # ==========================================
# if st.session_state.page == "home":
#     st.title("🐢 AI 海龜湯遊戲系統")
#     st.markdown("## 歡迎來到情境猜謎的世界！")
#     st.markdown("""
#     海龜湯是一種考驗邏輯思考與想像力的遊戲。
#     你將看到一個表面看似不合理、不完整的神祕事件，你需要透過不斷向 AI 主持人提問來抽絲剝繭，最終拼湊出完整的真相。
# 
#     ### 🎮 遊戲核心模式：
#     1. **提問模式**：您可以自由向 AI 提問，但主持人非常嚴格，只會回答:是、不是、與故事/題目無關、不完全是。
#     2. **認證完整答案模式**：當您在提問中拼湊出完整的真相後，切換至此模式提交答案。若答對核心，即可完美通關並解鎖完整謎底！
#     """)
# 
#     st.info("💡 準備好挑戰您的邏輯推理極限了嗎？點擊下方按鈕開始遊戲吧！")
#     if st.button(" 進入遊戲", use_container_width=True):
#         st.session_state.page = "game"
#         st.rerun()
# 
# elif st.session_state.page == "game":
#     st.title("AI海龜湯遊戲系統")
# 
#     st.sidebar.header("⚙️ 遊戲控制台")
# 
#     if st.sidebar.button("返回首頁", use_container_width=True):
#         st.session_state.page = "home"
#         st.rerun()
# 
#     riddle_titles = [item["title"] for item in riddle_bank]
# 
#     if "selectbox_title" not in st.session_state:
#         st.session_state.selectbox_title = riddle_titles[0]
# 
#     selected_title = st.sidebar.selectbox("📚 挑選題目：", riddle_titles, key="selectbox_title")
# 
#     current_puzzle = next(item for item in riddle_bank if item["title"] == selected_title)
#     riddle_text = current_puzzle["riddle"]
#     secret_answer_text = current_puzzle["secret_answer"]
# 
#     st.sidebar.markdown("---")
#     st.sidebar.subheader("🏁 已完成的題目紀錄")
#     if st.session_state.completed_riddles:
#         for solved in st.session_state.completed_riddles:
#             st.sidebar.button(
#                 f"✅ {solved}",
#                 key=f"nav_btn_{solved}",
#                 use_container_width=True,
#                 on_click=navigate_to_solved_riddle,
#                 args=(solved,)
#             )
#     else:
#         st.sidebar.write("💡 尚未有完成紀錄，加油！")
# 
#     if "current_title" not in st.session_state:
#         st.session_state.current_title = selected_title
#     if "chat_history" not in st.session_state:
#         st.session_state.chat_history = []
# 
#     if st.session_state.current_title != selected_title:
#         st.session_state.current_title = selected_title
#         if selected_title in st.session_state.completed_histories:
#             st.session_state.chat_history = list(st.session_state.completed_histories[selected_title])
#         else:
#             st.session_state.chat_history = []
#         st.rerun()
# 
#     st.info(f"### 當前湯面：\n\n {riddle_text}")
# 
#     game_mode = st.radio(
#         "請選擇互動模式：",
#         ["提問模式 (是非題尋找線索)", "認證完整答案模式 (提交真相)"],
#         horizontal=True
#     )
# 
#     st.divider()
# 
#     for message in st.session_state.chat_history:
#         current_avatar = "🔴" if message["role"] == "user" else "🍊"
#         with st.chat_message(message["role"], avatar=current_avatar):
#             st.markdown(message["content"])
# 
#     if user_input := st.chat_input("在下方輸入您的內容..."):
# 
#         with st.chat_message("user", avatar="🔴"):
#             st.markdown(user_input)
#         st.session_state.chat_history.append({"role": "user", "content": user_input})
# 
#         if game_mode == "提問模式 (是非題尋找線索)":
#             defense_prompt = f"""
#             你現在是專業海龜湯主持人。
#             題目：{riddle_text}
#             真相：{secret_answer_text}
#             玩家提問：{user_input}
#             【規則】：你只能回答以下四種字串之一，絕對不能解釋：
#             是、不是、與故事/題目無關、不完全是。
#             """
#         else:
#             defense_prompt = f"""
#             你現在是專業海龜湯主持人.
#             題目：{riddle_text}
#             真相：{secret_answer_text}
#             玩家提交了真相推論：{user_input}
#             【規則】：
#             1. 比對玩家答案是否抓到真相核心。
#             2. 如果玩家答對，請務必在回應開頭加上「🎉 恭喜完全答對！」並在此句之後公布這題的完整真相謎底（{secret_answer_text}）。
#             3. 如果玩家答錯，請告知玩家尚未抓到重點，並提示可换回提問模式。
#             """
# 
#         formatted_history = []
#         for msg in st.session_state.chat_history[:-1]:
#             formatted_history.append({"role": "user" if msg["role"] == "user" else "model", "parts": [msg["content"]]})
# 
#         try:
#             model = genai.GenerativeModel('gemini-flash-latest')
#             chat = model.start_chat(history=formatted_history)
# 
#             with st.spinner("主持人思考中..."):
#                 response = chat.send_message(defense_prompt)
#                 ai_reply = response.text.strip()
# 
#                 if game_mode == "提問模式 (是非題尋找線索)" and ai_reply not in ["是", "不是", "與故事/題目無關", "不完全是"]:
#                     ai_reply = "與故事/題目無關"
# 
#                 if "🎉 恭喜完全答對！" in ai_reply:
#                     if selected_title not in st.session_state.completed_riddles:
#                         st.session_state.completed_riddles.append(selected_title)
# 
#                 with st.chat_message("assistant", avatar="🍊"):
#                     st.markdown(ai_reply)
#                 st.session_state.chat_history.append({"role": "assistant", "content": ai_reply})
# 
#                 if selected_title in st.session_state.completed_riddles:
#                     st.session_state.completed_histories[selected_title] = list(st.session_state.chat_history)
# 
#         except Exception as e:
#             st.error(f"Gemini 連線錯誤: {e}")

# 1. 強制殺掉背景可能殘留、佔用 Port 的舊 Streamlit 程序
!pkill -f streamlit

# 2. 下載並安裝穩定版 Cloudflare Tunnel
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

# 3. 同時啟動 Streamlit 與 Cloudflare 外網穿透
print("\n=== ✨ 請在下方跑出來的文字中，尋找 .trycloudflare.com 結尾的全新網址進入！ ===")
!streamlit run app.py & cloudflared tunnel --url http://localhost:8501